account/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/<int:pk>', views.profile, name='profile'),
]

echorder/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('restaurant.urls')),
    path('account/', include('account.urls')),

    # password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'),
         name='password_change_done'),
    path('password_change/',
         auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'),
         name='password_change'),
    path('password_reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password_reset/',
         auth_views.PasswordResetView.as_view(),
         name='password_reset'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'),
         name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate

from .models import Account

class RegistrationForm(UserCreationForm):
    acc = Account()
    email = forms.EmailField(max_length=255, help_text="Add a valid email address")
    category = forms.ChoiceField(choices=acc.CATEGORY, help_text="Select a valid category")

    class Meta:
        model = Account
        fields = ['email', 'username', 'category', 'password1', 'password2']

    def clean_email(self):
        email = self.cleaned_data['email'].lower()

        try:
            account = Account.objects.get(email=email)
        except Exception as e:
            return email
        raise forms.ValidationError(f"Email '{email}' is already in use.")


    def clean_username(self):
        username = self.cleaned_data['username']

        try:
            account = Account.objects.get(username=username)
        except Exception as e:
            return username
        raise forms.ValidationError(f"Username '{username}' is already in use.")


class AccountAuthenticationForm(forms.ModelForm):
    password = forms.CharField(label="Password", widget=forms.PasswordInput)

    class Meta:
        model = Account
        fields = ['email', 'password']

    def clean(self):
        if self.is_valid():
            email = self.cleaned_data['email']
            password = self.cleaned_data['password']
            if not authenticate(email=email, password=password):
                raise forms.ValidationError('Invalid Login')

templates/password_reset/password_change.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1 class="text-success text-center">Change your password</h1>
<div class="card bg-dark text-white">
    <img src="{% static 'images/deliver.jpg' %}" class="card-img" alt="...">
    <div class="card-img-overlay">
        <h5 class="card-title text-center">Change Password</h5>
        <form action="" method="post">
            <div class="card-text">
            {% csrf_token %}
                <div class="mb-3 row">
                    <label for="inputPassword" class="col-md-2 offset-md-2 form-label">Old Password:</label>
                    <div class="col-md-5">
                        <input name="old_password" type="password" class="form-control" id="inputPassword" placeholder="Old Password" required>
                    </div>
                </div>

                <div class="mb-3 row">
                    <label for="inputPassword1" class="col-md-2 offset-md-2 col-form-label">Password:</label>
                    <div class="col-md-5">
                        <input name="new_password1" type="password" class="form-control" id="inputPassword1" placeholder="New Password" required>
                    </div>
                </div>

                <div class="mb-3 row">
                    <label for="inputPassword2" class="col-md-2 offset-md-2 col-form-label">Password:</label>
                    <div class="col-md-5">
                        <input name="new_password2" type="password" class="form-control" id="inputPassword2" placeholder="Confirm Password" required>
                    </div>
                </div>

                {% for field in form %}
                <p>
                    {% for error in field.errors %}
                        <p class="bg-warning fw-bold text-center text-danger rounded">{{ error }}</p>
                    {% endfor %}
                </p>
                {% endfor %}

                {% if form.non_field_errors %}
                <div class="text-danger">
                    <p class="bg-warning text-center fw-bold rounded">{{ form.non_field_errors }}</p>
                </div>
                {% endif %}

                <div class="mt-5 row">
                    <input type="submit" class="btn btn-success col-md-2 offset-md-5" value="Update Password">
                </div>

            <!--      <div class="mb-3">-->
            <!--        <label for="formFile" class="form-label">Default file input example</label>-->
            <!--        <input class="form-control" type="file" id="formFile">-->
            <!--      </div>-->
            </div>
        </form>

        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        <p class="card-text">Last updated 3 mins ago</p>
    </div>
</div>
{% endblock %}

{% block style %}
    img.card-img {
        opacity: 0.5;
    }
{% endblock %}

templates/password_reset/password_change_done.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1 class="text-success text-center">Password Change Done</h1>
<div class="card bg-dark text-white">
    <img src="{% static 'images/deliver.jpg' %}" class="card-img" alt="...">
    <div class="card-img-overlay">
        <h2 class="card-title text-center">Your Password Has Been Updated</h2>
    </div>
</div>
{% endblock %}

{% block style %}
    img.card-img {
        opacity: 0.5;
    }
{% endblock %}

templates/password_reset/password_reset_complete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1 class="text-success text-center">Password Change Done</h1>
<div class="card bg-dark text-white">
    <img src="{% static 'images/deliver.jpg' %}" class="card-img" alt="...">
    <div class="card-img-overlay">
        <h2 class="card-title text-center">
            Your Password Has Been Reset. You may go ahead and <a href="{% url 'login' %}">login</a> now
        </h2>
    </div>
</div>
{% endblock %}

{% block style %}
    img.card-img {
        opacity: 0.5;
    }
{% endblock %}

templates/password_reset/password_reset_done.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1 class="text-success text-center">Password Reset Done</h1>
<div class="card bg-dark text-white">
    <img src="{% static 'images/deliver.jpg' %}" class="card-img" alt="...">
    <div class="card-img-overlay">
        <div class="card-text d-block mx-auto text-center" >
            <p>We have emailed you instructions for setting your password,
            if an account exists with the email you have entered, you should receive them shortly.</p>

            <p>If you don't receive an email, please make sure you have entered the address you
            registered with, and check your spam folder.</p>
            <p class="bg-dark p-3 rounded"><a href="{% url 'home' %}">Return to Homepage</a></p>
        </div>
    </div>
</div>
{% endblock %}

{% block style %}
    img.card-img {
        opacity: 0.5;
    }
    .card-text {
        width: 500px;
        height: auto;
    }
{% endblock %}

templates/password_reset/password_reset_email.html
{% autoescape off %}
To initiate the password reset process for your Account {{ user.email }},
click the link below:
{{ protocol }}: //{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

If clicking the link above doesn't work, please copy and paste the url in a new browser window instead.

Sincerely,
The e-Chorder Team
{% endautoescape %}

templates/password_reset/password_reset_form.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1 class="text-success text-center">Reset your password</h1>
<div class="card bg-dark text-white">
    <img src="{% static 'images/deliver.jpg' %}" class="card-img" alt="...">
    <div class="card-img-overlay">
        <h5 class="card-title text-center">Reset Password</h5>
        <form action="" method="post">
            <div class="card-text">
            {% csrf_token %}
                <div class="mb-3 row">
                    <div class="col-md-5">
                        <input name="email" type="email" class="form-control" id="id_email" placeholder="Email Address" required>
                    </div>
                </div>

                <div class="mt-5 row">
                    <input type="submit" class="btn btn-success col-md-2 offset-md-5" value="Send Reset Email">
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

{% block style %}
    img.card-img {
        opacity: 0.5;
    }
{% endblock %}